### ISSUE TITLE
Allow for multiple template IDs in C# SDK TemplateSignatureRequest

### ISSUE THREAD

**Issue by johnnycupcakes** [HelloFax/hellosign-dotnet-sdk#15]
Does the C# SDK support passing in multiple Template IDs on the TemplateSignatureRequest object that you pass into CreateEmbeddedSignatureRequest?

It seems as though TemplateSignatureRequest.TemplateId is just a string.

If not, is there any other easy way to do this. I am doing everything right now using the C# SDK.

**Comment by BHSPitMonkey** [comment]
This is now supported. See release notes for release 0.4 here:

https://github.com/HelloFax/hellosign-dotnet-sdk/releases/tag/v0.4.0.0
