### ISSUE TITLE
Support .NET Framework 3.5

### ISSUE THREAD

**Issue by BHSPitMonkey** [HelloFax/hellosign-dotnet-sdk#16]

**Comment by BHSPitMonkey** [comment]
Attached is an experimental build with .NET 3.5 as the build target. Some tweaks were made to abandon some .NET 4.x features. The changes can be seen in commit 8b3c810.

[hellosign-dotnet35-test.zip](https://github.com/HelloFax/hellosign-dotnet-sdk/files/237964/hellosign-dotnet35-test.zip)

Testing welcome!

**Comment by renderf0x** [comment]
Awesome, thanks @BHSPitMonkey -- I think this has been sent along.

**Comment by BHSPitMonkey** [comment]
This landed in 0.5.1.
