### ISSUE TITLE
It would be useful if the SDK were available as a NuGet package

### ISSUE THREAD

**Issue by radhack** [HelloFax/hellosign-dotnet-sdk#17]
Are there any plans for this to happen in the near future? If not, would it be okay for me to add it to our private NuGet feed as a temporary measure?

**Comment by BHSPitMonkey** [comment]
Definitely planned. I'm not completely aware of the implications of adding it to your private feed, but if it's private / local to your organization then I don't see why not!

**Comment by xt0rted** [comment]
This is available on NuGet now https://www.nuget.org/packages/HelloSign/

**Comment by BHSPitMonkey** [comment]
Indeed it is! Apologies for forgetting to close the issue and notify you.
