### ISSUE TITLE
Are there any plans to add async support?

### ISSUE THREAD

**Issue by xt0rted** [HelloFax/hellosign-dotnet-sdk#20]
The project I'm working on has a custom implementation using `HttpClient` and is all async. I'd like to switch over to this instead but without async support I can't.

**Comment by BHSPitMonkey** [comment]
There are no plans for this currently, but I think you should be able to wrap calls to this client in async functions pretty easily.

**Comment by RPM1984** [comment]
@BHSPitMonkey hi there 👋 ! been a while since this issue was reported, so just checking in if this is now on the roadmap?

**Comment by BHSPitMonkey** [comment]
@RPM1984 Unfortunately not at this time, but I've notified our product team of the request and we'll keep this in mind as a potential future improvement. Thanks for the feedback!
