### ISSUE TITLE
Add Document Model and Documents list to Template Model 

### ISSUE THREAD

**Issue by jhstrateng** [HelloFax/hellosign-dotnet-sdk#21]
The SDK does not include an implementation for the Document Model nor its corresponding Form Fields. Our company is evaluating purchasing a subscription to HelloSign. One of the features we are looking for is the ability to use Form Fields pulled from a Template object, but sent with varying PDFs. Similar to the scenario described on the developer site, Template Walkthroughs, titled, "Using Files and Form Fields"

**Comment by BHSPitMonkey** [comment]
@jhstrateng - I just pushed out a new release (0.5.2.0) to NuGet and our GitHub Releases page. Please reopen this issue if it doesn't meet your needs.

The following code should now be usable:

``` csharp
var templates = client.ListTemplates();
foreach (Template template in templates) {
    foreach (Document doc in template.Documents) {
        Console.WriteLine("Doc name: " + doc.Name);
        foreach (var field in doc.CustomFields) {
            Console.WriteLine("CustomField:");
            Console.WriteLine(" Name: " + field.Name);
            Console.WriteLine(" API ID: " + field.ApiId);
            Console.WriteLine(" Required: " + (field.Required ? "yes" : "no"));
            Console.WriteLine(" Type: " + field.Type);
        }
    }
}
```
