### ISSUE TITLE
Add support for the /update endpoint

### ISSUE THREAD

**Issue by radhack** [HelloFax/hellosign-dotnet-sdk#26]
Support the POST /signature_request/update endpoint and the posible parameters.

**Comment by iamadamreed** [comment]
If this could please be implemented as soon as possible, it is greatly needed.

**Comment by iamadamreed** [comment]
Could we get a Milestone on this?

**Comment by BHSPitMonkey** [comment]
Sincere apologies for the lack of updates here! This was added in January 2017 with version 0.5.5.
