### ISSUE TITLE
client.AddMemberToTeam fails with MethodNotAllowedException

### ISSUE THREAD

**Issue by rich-jobadder** [HelloFax/hellosign-dotnet-sdk#27]
When trying to call AddMemberToTeam, it looks like internally it's trying to use GET rather than POST.

Error Received:

HelloSign.MethodNotAllowedException: GET is not supported for this URI

**Comment by rich-jobadder** [comment]
ditto with client.AddAccountToTemplate

**Comment by alexmac05** [comment]
Hi Rich,

We are looking at prioritizing these SDK issues, is this still important to you?
Could you pick one of these priorities?
1. Deal Breaker
2. An important enhancement for us
3. Nice to have but not top of mind
4. We have already found a workaround and no longer are concerned with this

Thank you! 
Alex M. 
apisupport@hellosign.com
internal issue as-44
