### ISSUE TITLE
Add support for Decline to Sign

### ISSUE THREAD

**Issue by desmondw** [HelloFax/hellosign-dotnet-sdk#28]
The following changes have been made to the API:
- There is a new parameter allow_decline for declining to sign signature requests
- There is a new API status_code for declined requests
- There is a new API variable is_declined on SignatureRequest objects
- There is a new API variable decline_reason on Signature objects

**Comment by quanlee** [comment]
allow_decline has been added
https://github.com/HelloFax/hellosign-dotnet-sdk/commit/e32d0fd039dae3dd5f7852d3470b4bdd4811c5cb
