### ISSUE TITLE
HelloSignTestApp/Program.cs defaults to staging and not production

### ISSUE THREAD

**Issue by alexmac05** [HelloFax/hellosign-dotnet-sdk#33]
https://github.com/HelloFax/hellosign-dotnet-sdk/blob/v3/HelloSignTestApp/Program.cs

this defaults to staging and not production

and this results in an authorization error which confuses users.

**Comment by BHSPitMonkey** [comment]
The TestApp project isn't really intended to be built or executed by users outside of this SDK's maintainers/contributors; In the future this will hopefully be replaced by a proper test suite that isn't dependent on the backend at all. As such, I think this can slide for now!
