### ISSUE TITLE
Add support for Allow Reassign

### ISSUE THREAD

**Issue by tommy5dollar** [HelloFax/hellosign-dotnet-sdk#35]
[HelloSign added the ability for Signer Reassignment in March 2017](http://blog.hellosign.com/signer-reassignment-removes-frustrating-roadblocks/)

Could this please be implemented in the API? It should be as simple as adding a new boolean called `allow_reassign` to the Signature Request, in the style of `allow_decline`.

**Comment by tommy5dollar** [comment]
I submitted a [pull request](https://github.com/HelloFax/hellosign-dotnet-sdk/pull/36) a week ago, could somebody merge this in, please?

**Comment by BHSPitMonkey** [comment]
Apologies for the delay in responding to this! Because the PR exists, I'll go ahead and close this Issue and continue this discussion on #36.
