### ISSUE TITLE
Add support for allow decline in CreateUnclaimedDraft

### ISSUE THREAD

**Issue by unnijeevan** [HelloFax/hellosign-dotnet-sdk#38]
The function UnclaimedDraft _CreateUnclaimedDraft is missing 
    if (signatureRequest.AllowDecline) request.AddParameter("allow_decline", "1");

The endpoint supports allow_decline 
https://app.hellosign.com/api/reference#create_unclaimed_draft

**Comment by alexmac05** [comment]
Hi Jeevan, 

I have reached out to you from apisupport@hellosign.com to see if this is still important to you. 

Thank you. Cheers,
alex m
internal issue number as-52
