### ISSUE TITLE
oAuth functionality needs to be added

### ISSUE THREAD

**Issue by alexmac05** [HelloFax/hellosign-dotnet-sdk#41]
The ability to pass oAuth creds through the C# sdk should be added. Currently does not support oAuth.

**Comment by Framinus** [comment]
Raw HTTP request calls using the [RestSharp](restsharp.org) library:

To retrieve the OAuth Token (the state and code are returned from your authorization url, and the api key from your account):

`static void RetrieveOAuthToken(string apiKey, string code, string state) {
            var key = apiKey;
            var httpClient = new RestClient("https://app.hellosign.com");
            httpClient.Authenticator = new RestSharp.Authenticators.HttpBasicAuthenticator(key, "");
            var request = new RestRequest("oauth/token", Method.POST);
            request.AddParameter("state", state);
            request.AddParameter("code", code);
            request.AddParameter("grant_type", "authorization_code");
            request.AddParameter("client_id", "YOUR_CLIENT_ID");
            request.AddParameter("client_secret", "YOUR_CLIENT_SECRET");
            IRestResponse response = httpClient.Execute(request);
            var content = response.Content; 
            Console.WriteLine(content);
        }`

To refresh the OAuth Token (the refresh token is returned in the RetrieveOAuthToken function):

`static void RefreshOAuthToken(string refreshCode) {
            var httpClient = new RestClient("https://app.hellosign.com");
            var request = new RestRequest("oauth/token", Method.POST);
            request.AddParameter("grant_type", "refresh_token");
            request.AddParameter("refresh_token", refreshCode);
            IRestResponse response = httpClient.Execute(request);
            var content = response.Content;
            Console.WriteLine(content);
        }`

A sample signature request using the OAuth token:

`static void OAuthSignatureRequest(string accessToken) {
            var httpClient = new RestClient("https://api.hellosign.com/v3/");
            var request = new RestRequest("signature_request/send", Method.POST);
            request.AddParameter("Authorization", string.Format("Bearer " + accessToken), ParameterType.HttpHeader);
            request.AddParameter("title", "Please sign");
            string prefix = String.Format("signers[{0}]", "0");
            request.AddParameter(prefix + "[email_address]", "james@example.com");
            request.AddParameter(prefix + "[name]", "James");
            request.AddFile("testing", "testing.pdf");
            request.AddParameter("signing_options", "{\"draw\": true, \"type\": true, \"upload\": true, \"phone\": false, \"default\": \"draw\"}");
            IRestResponse response = httpClient.Execute(request);
            var content = response.Content;
            Console.WriteLine(content);
        }`
