### ISSUE TITLE
Update HelloSign.nuspec with actual range of allowed dependencies

### ISSUE THREAD

**Issue by HapHazard1** [HelloFax/hellosign-dotnet-sdk#42]
You currently have just a single version number for your dependencies (Newtonsoft.Json and RestSharp).  This forces versions of these dependencies to be at least that version.  Instead you should specify the range of allowed versions e.g. "<dependency id="Newtonsoft.Json" version="[6.0.0,10.0.0)" />".  We are using HelloSign 0.5.5. with Newtonsoft.Json version 6.0.3 without problems but we have to go through a big pain to make sure nuget doesn't try to replace our Newtonsoft.Json with a more recent version which breaks other dependencies.

**Comment by alexmac05** [comment]
Hi HapHazard1, I take it this is still an issue for you. Can you write me at apisupport@hellosign.com? We are looking into these issues and will soon start to address them. Thank you. 
Cheers,
Alex M. 
internal issue number AS-51
