### ISSUE TITLE
Add in the C# SDK the editor parameter for custom fields (Workaround documented here)

### ISSUE THREAD

**Issue by alexmac05** [HelloFax/hellosign-dotnet-sdk#47]
Add in the C# SDK the editor parameter for custom fields (Workaround documented here)

For signature requests that send the request using a template:
v3/signature_request/send_with_template is one example

The API Supports making an editable custom field 

https://faq.hellosign.com/hc/en-us/articles/216599897-How-do-I-use-Editable-Merge-Fields-aka-Custom-Fields-

in the case where there is only one signer. 

This issue is to request the ability to add the editor parameter to the SDK. A workaround is to use RestSharp directly

example code:
 `try
{
var hslogin = "your EMAIL ADDRESS";
var hspassword = "Your Password";
var apiKey = "API KEY";
 
 

var restClient = new RestClient();

string buildTheRequest = "https://" + apiKey + ":@api.hellosign.com";
Console.WriteLine(buildTheRequest);

restClient.BaseUrl = new Uri(buildTheRequest);
restClient.Authenticator = new HttpBasicAuthenticator(hslogin, hspassword);

var request = new RestRequest();
request.Resource = "v3/signature_request/send_with_template";
request.Method = Method.POST;
request.AddParameter("template_id", "TEMPLATE ID HERE");
 
request.AddParameter("title", "test");
request.AddParameter("message", "testing");
request.AddParameter("signers[Client][name]", "George");
request.AddParameter("signers[Client][email_address]", "emailAddress@example.com");

request.AddParameter("custom_fields", "[{\"name\":\"fName\",\"value\":\"alex\",\"editor\":\"Client\"}]");

request.AddParameter("test_mode", 1);

IRestResponse response = restClient.Execute(request);

Console.WriteLine(response.Content);

if (response.ErrorException != null)
                        {
const string message = "Error retrieving response.  Check inner details for more info.";
var helloSignException = new ApplicationException(message, response.ErrorException);
throw helloSignException;
                        }
                    }
catch (Exception ex)
                    {
Console.WriteLine(ex.Message, ex.InnerException.Message);
                    }

                }`

**Comment by alexmac05** [comment]
internal issue number AS-58

**Comment by BHSPitMonkey** [comment]
This will be included with #53
