### ISSUE TITLE
Add Ability to Specify Page of Document for Custom Fields

### ISSUE THREAD

**Issue by drweb86-work** [HelloFax/hellosign-dotnet-sdk#48]
Hello

It would be nice if i could specify page number of document where to put custom field on.

Thanks

**Comment by radhack** [comment]
Hi @drweb86-work - could you clarify your suggestion? customFields are fields that are already placed on HelloSign templates, so I'm a little confused about how or where you'd specify a page number for them.

Are you maybe talking about formFieldsPerDocument? If that's the case, you can add the page to the json array:

```
[
  [
    {
      "api_id":"uniqueIdHere_1",
      "name":"",
      "type":"text",
      "x":112,
      "y":328,
      "width":100,
      "height":16,
      "required":true,
      "signer":1,
      "validation_type":"numbers_only",
      "page":2
    },
    {
      "api_id":"uniqueIdHere_2",
      "name":"",
      "type":"signature",
      "x":530,
      "y":415,
      "width":120,
      "height":30,
      "required":true,
      "signer":0,
      "page":1
    }
  ]
]
```

**Comment by radhack** [comment]
@drweb86-work just circling back around to get clarification. Let us know what the use case is or if it was indeed form_fields_per_document that you were thinking of and we'll go from there.
