### ISSUE TITLE
Could not load type 'HelloSign.Client'

### ISSUE THREAD

**Issue by shakeelsadiq** [HelloFax/hellosign-dotnet-sdk#51]
I have created a new MVC application targeting .Net 4.7.1 and added the HelloSign NuGet package v0.5.7.  On running the application I get:

Could not load type 'HelloSign.Client' from assembly 'HelloSign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by shakeelsadiq** [comment]
Just as a note; I have used RestSharp and consumed the HelloSign API directly without the Client and that works fine as expected.

**Comment by BHSPitMonkey** [comment]
I'm sorry to see that, and double sorry for not responding to this sooner! I haven't heard of similar reports and can't currently reproduce this problem myself, so I'm going to mark this issue closed for the time being; If this is still a problem for you, please reopen and attach any relevant code or project files you can share to help us figure out what could be the cause.
