### ISSUE TITLE
Strongly name the assembly

### ISSUE THREAD

**Issue by mrkoggles** [HelloFax/hellosign-dotnet-sdk#55]
RestSharp dependency needs to be updated to signed version.
Add .snk file and update .csproj file to sign.

**Comment by mrkoggles** [comment]
pull request link: https://github.com/hellosign/hellosign-dotnet-sdk/pull/56/files

**Comment by BHSPitMonkey** [comment]
This has been shipped in version 1.3.0. Thanks for your report and pull request, and please let us know if you encounter any issues!
