### ISSUE TITLE
Signature class is missing Error property

### ISSUE THREAD

**Issue by Framinus** [HelloFax/hellosign-dotnet-sdk#58]
The HelloSign .net SDK Signature class is missing the Error property - is it supposed to be the DeclineReason property instead of Error? I assume the text in the 'error' tag should be deserialized into the DeclineReason property?

The value from 'error' is not being deserialized into the object (probably due to the name mismatch).

**Comment by BHSPitMonkey** [comment]
This is fixed as of v0.5.9! Thanks again for the report.
