### ISSUE TITLE
Support argument 'name' with /signature_request/remind/[:signature_request_id]

### ISSUE THREAD

**Issue by radhack** [HelloFax/hellosign-dotnet-sdk#6]
Allow for the argument 'name' to be supported when hitting /signature_request/remind/[:signature_request_id]

**Comment by jmithy** [comment]
Hello,

Could you let me know an expected completion date ?

**Comment by BHSPitMonkey** [comment]
This has been fixed; Apologies for the long wait.

You can download a new build here: https://github.com/HelloFax/hellosign-dotnet-sdk/releases
