### ISSUE TITLE
Adding signing_options feature to all signature request endpoints.

### ISSUE THREAD

**Issue by Framinus** [HelloFax/hellosign-dotnet-sdk#61]
Adding the signing_options parameter to all non-embedded and embedded signature request endpoints. 

ie:
signing_options = {"draw": true, "type": true, "upload": true, "phone": false, "default": "draw"}

**Comment by BHSPitMonkey** [comment]
This is now supported as of v0.5.9! Here's how to use it:

```csharp
request.SigningOptions = new SigningOptions
{
    Draw = true,
    Type = true,
    Upload = true,
    Phone = false
    Default = "draw"
};
```

Thanks again for the report!
