### ISSUE TITLE
Maximum RestSharp Package Version

### ISSUE THREAD

**Issue by Patman0021** [HelloFax/hellosign-dotnet-sdk#67]
Is there a reason why the maximum version of RestSharp is 106.5.4?

I understand that this was requested in https://github.com/hellosign/hellosign-dotnet-sdk/issues/42#issue-256345468 but this is causing issues with the HelloSign package not allowing me to use the latest RestSharp version.

**Comment by BHSPitMonkey** [comment]
Hi! Versions 106.6.* of RestSharp make some big backwards-incompatible changes, particularly having to do with JSON (de)serialization, which don't work with the current codebase. Based on the project's current [note about JSON serialization](https://github.com/restsharp/RestSharp/tree/e2d0bfd99de7aa5651d713e48d728d342195877d#note-on-json-serialization), it might be easier to update to version 107 when it becomes available. Apologies for any inconvenience caused!
