### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by dwhittlesey** [HelloFax/hellosign-dotnet-sdk#7]
I have the api key installed and am using the demo I pulled off Git.  I keep getting the following error:

{"No connection could be made because the target machine actively refused it 184.168.221.47:443"}

stack trace  =  at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)

**Comment by BHSPitMonkey** [comment]
Hi @dwhittlesey,

The HelloSignTestApp program defaults to our internal "staging" environment, which is probably what is happening in your case. If you specify "prod" as the first argument when running the program, it will connect to api.hellosign.com instead. Sorry for the confusion.

So, running the program should look something like:

```
HelloSignTestApp.exe prod
```
