### ISSUE TITLE
Update test app apiHost endpoint

### ISSUE THREAD

**Issue by janetanne** [HelloFax/hellosign-dotnet-sdk#76]
Update:
`string apiHost = "api.staging-hellosign.com";
Console.WriteLine("Using HelloSign API at host: " + apiHost);`

to 

`string apiHost = "app.hellosign.com";
Console.WriteLine("Using HelloSign API at host: " + apiHost);`

(Internal reference number: 412112)

**Comment by janetanne** [comment]
Adding another comment as another customer ran into this issue as well.

Internal reference number: 431554

**Comment by BHSPitMonkey** [comment]
As of v1.4.0, HelloSignTestApp now accepts the target host via a (required) `APIHOST` environment variable (similar to how `APIKEY` is passed in).

This is now documented here: [tests/HelloSignTestApp/README.md](https://github.com/hellosign/hellosign-dotnet-sdk/blob/v3/tests/HelloSignTestApp/README.md)
