### ISSUE TITLE
Allow setting client id for non-embedded signature requests

### ISSUE THREAD

**Issue by jordanwallwork** [HelloFax/hellosign-dotnet-sdk#9]
I need to be able to create signature requests where the user signs the document through your website, but the endpoint notified of any views/signs etc is an individual client app. Currently you can only get app callbacks by calling `CreateEmbeddedSignatureRequest`

**Comment by BHSPitMonkey** [comment]
Thanks for pointing this out; The current implementation came before we began supporting this on the backend. I'll take a look at your changes when I have some time.

**Comment by BHSPitMonkey** [comment]
This is now supported via an optional parameter:

``` c#
public SignatureRequest SendSignatureRequest(SignatureRequest signatureRequest, string clientId = null)
public TemplateSignatureRequest SendSignatureRequest(TemplateSignatureRequest signatureRequest, string clientId = null)
```
