### ISSUE TITLE
NuGet package is still 1.3.0 and the latest available is 1.4.0

### ISSUE THREAD

**Issue by Patman0021** [HelloFax/hellosign-dotnet-sdk#95]
Could we get someone to update the Nuget package in Nuget?
GitHub:
[https://github.com/hellosign/hellosign-dotnet-sdk/releases](https://github.com/hellosign/hellosign-dotnet-sdk/releases)
NuGet:
[https://www.nuget.org/packages/HelloSign/](https://www.nuget.org/packages/HelloSign/)

**Comment by mattoosterbaan** [comment]
I second this. I'd love to see my simple pull request get accepted and then a new Nuget package.

**Comment by alexmac05** [comment]
Yes, thank you for this. We will look into this next week.

**Comment by erosiec** [comment]
**IR: 11797**

**Comment by Patman0021** [comment]
So, latest release is now 1.5.0.  1.3.0 is still what's on nuget...

**Comment by kennydust** [comment]
whats the backstory on why 1.5.0 isn't available on nuget?

**Comment by Phlank** [comment]
It looks like they simply haven't updated their API key for NuGet in their CI build process. This should be a simple fix, but who knows when it will get done. It doesn't look like this package is currently a high priority.

It's also possible that whoever was managing this package in NuGet left the company and didn't leave behind credentials to access it or transfer ownership of the NuGet package to someone else. If that's the case, it may take them some time to recover the package and start deploying to NuGet again.

![image](https://user-images.githubusercontent.com/5016241/118988530-453b4800-b94f-11eb-9b2c-3be607b13a6d.png)

**Comment by aarifResaas** [comment]
Is there any progress @alexmac05 ?

**Comment by Patman0021** [comment]
Ya alexmac05 is at Twilio now, no longer at HelloSign :\

**Comment by Patman0021** [comment]
So, it looks like 1.5.0 is available on nuget now.  Closing this issue.

**Comment by aarifResaas** [comment]
Am I missing something?  I still only see v1.3.0.

https://www.nuget.org/packages/HelloSign/
